# Stage 1: Build the Next.js app
# This stage builds the Next.js application into an optimized production-ready output.
FROM node:22-slim AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package manager files to leverage Docker's layer caching.
COPY package*.json ./

# Install dependencies using 'npm ci' for faster, reproducible builds
RUN npm ci

# Copy the rest of the application source code into the container
COPY . .

# Pass the public Clerk key as a build-time argument
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY

# Build the Next.js application for production
RUN npm run build

# Stage 2: Create the final, lightweight production image
# This stage takes only the necessary built files from the 'builder' stage
# to create a small and secure final image.
FROM node:22-slim AS runner

WORKDIR /app

# Set the environment to 'production' which optimizes Next.js
ENV NODE_ENV=production

# Copy the standalone output from the builder stage.
# This was generated by the `output: 'standalone'` config in next.config.ts
# and contains a minimal server and only the necessary production node_modules.
COPY --from=builder /app/.next/standalone ./

# Copy the public assets from the builder stage
COPY --from=builder /app/public ./public

# Copy the built static assets (CSS, JS, etc.) from the builder stage
COPY --from=builder /app/.next/static ./.next/static

# Expose port 3000 to allow traffic to the container
EXPOSE 3000

# Set the port environment variable that the Next.js server will listen on
ENV PORT=3000

# The command that will be executed to start the application
# We explicitly bind to all interfaces and honor PORT (default 3000)
CMD ["sh", "-c", "node server.js --hostname 0.0.0.0 --port ${PORT:-3000}"]
